replicaCount: 2

image:
  repository: YOUR_AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/eks-helm-demo
  tag: "latest"
  pullPolicy: IfNotPresent

containerPort: 8080

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

environment: default

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 256Mi

ingress:
  enabled: false

  className: alb

  annotations: {}

  host: demo.example.com
